=== Kronmar-Bafu/linpy/py_cube/description.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Name": {
      "type": "object",
      "properties": {
        "de": { "type": "string" },
        "fr": { "type": "string" },
        "it": { "type": "string" },
        "en": { "type": "string" }
      },
      "required": ["de", "en"]
    },
    "Description": {
      "type": "object",
      "properties": {
        "de": { "type": "string" },
        "en": { "type": "string" }
      },
      "required": ["de", "en"]
    },
    "Publisher": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Publisher"
      }
    },
    "Creator": {
      "$ref": "#/definitions/Creator"
    },
    "Contributor": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Contributor"
      }
    },
    "Themes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Theme"
      }
    },

    "Date Created": {
      "type": "string",
      "format": "date-time"
    },
    "Contact Point": {
      "$ref": "#/definitions/ContactPoint"
    },
    "Base-URI": {
      "type": "string"
    },
    "Identifier": {
      "type": "string"
    },
    "Version": {
      "type": "number"
    },
    "Work Status": {
      "type": "string",
      "enum": ["Draft", "In Progress", "Published", "Obsolete"]
    },
    "Visualize": {
      "type": "boolean"
    },
    "Accrual Periodicity": {
      "type": "string",
      "enum": ["daily", "weekly", "monthly", "quarterly", "yearly"]
    },
    "Namespace": {
      "type": "string"
    },
    "dimensions": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "$ref": "#/definitions/Dimension"
        }
      },
      "additionalProperties": true
    }
  },

  "required": [
    "Name",
    "Description",
    "Publisher",
    "Creator",
    "Contributor",
    "Date Created",
    "Contact Point",
    "Base-URI",
    "Identifier",
    "Version",
    "Work Status",
    "Visualize",
    "Accrual Periodicity",
    "Namespace",
    "dimensions"
  ],
  "definitions": {
    "Publisher": {
      "type": "object",
      "properties": {
        "IRI": {
          "type": "string"
        }
      },
      "required": ["IRI"]
    },
    "Creator": {
      "type": "object",
      "properties": {
        "IRI": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": ["IRI"]
    },
    "Contributor": {
      "type": "object",
      "properties": {
        "IRI": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": ["IRI", "Name"]
    },
    "Theme": {
      "type": "object",
      "properties": {
        "IRI": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": ["IRI"]
    },
    "ContactPoint": {
      "type": "object",
      "properties": {
        "E-Mail": {
          "type": "string",
          "format": "email"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": ["E-Mail", "Name"]
    },
    "Dimension": {
      "type": "object",
      "properties": {
        "name": {
          "type": "object",
          "properties": {
            "de": { "type": "string" },
            "fr": { "type": "string" },
            "it": { "type": "string" },
            "en": { "type": "string" }
          },
          "required": ["de", "en"]
        },
        "dimension-type": {
          "type": "string",
          "enum": ["Key Dimension", "Measure Dimension", "Standard Error"]
        },
        "data-kind": {
          "type": "object",
          "description": "See https://cube.link/#meta-datakind-temporal-spatial",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["temporal", "spatial-shape", "spatial-coordinates"]
            },
            "unit": {
              "type": "string"
            }
          }
        },
        "scale-type": {
          "description": "See https://cube.link/#qudt-scaletype",
          "type": "string",
          "enum": ["nominal", "ordinal", "interval", "ratio"]
        },
        "mapping": {
          "type": "object",
          "properties": {
            "value-type": {
              "type": "string",
              "enum": ["Shared", "Literal"]
            },
            "type": {
              "type": "string",
              "enum": ["regex", "lookup", "replace", "additive"]
            },
            "pattern": {
              "type": "string"
            },
            "replacement": {
              "type": "string"
            },
            "replacements": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "base": {
              "type": "string"
            }
          },
          "allOf": [
            {
              "if": {
                "properties": { "type": { "const": "regex" } }
              },
              "then": {
                "required": ["pattern", "replacement"]
              }
            },
            {
              "if": {
                "properties": { "type": { "const": "replace" } }
              },
              "then": {
                "required": ["replacements"]
              }
            },
            {
              "if": {
                "properties": { "type": { "const": "additive" } }
              },
              "then": {
                "required": ["base"]
              }
            }
          ]
        },
        "unit": {
          "type": "string"
        },
        "path": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "dimension-type",
        "scale-type",
        "path",
        "description"
      ]
    }
  }
}

=== Kronmar-Bafu/linpy/example/corona/description.json
{
  "$schema": "../../py_cube/description.schema.json",
  "Name": {
    "de": "Corona-Zahlen Zeitverlauf",
    "en": "Corona Numbers Timeline"
  },
  "Description": {
    "de": "Zeitreihe der Corona-Zahlen für Schleswig-Holstein\r\n\r\nEnthalten sind folgende Felder:\r\n\r\n- `Datum` - Datum im Format TT.MM.JJJJ\r\n- `Gemeldete Fälle`\r\n- `Hospitalisierungen`\r\n- `Verstorben`\r\n\r\nFeldtrenner ist Komma, Zeichenketten-Trenner ist doppeltes Anführungszeichen (\")\r\n\r\nBasis für die hier veröffentlichten Daten sind die Zahlen, die die Kreise und kreisfreien Städte auf dem offiziellen Meldeweg der Landesmeldestelle mitteilen. Da die Datenerfassung und Übermittlung Zeit benötigt, können Abweichungen von den vor Ort kommunizierten Fällen entstehen. Im Einzelfall kann es auch zu einer Reduzierung der gemeldeten Fälle kommen, zum Beispiel wenn sich eine Meldung nicht bestätigt hat oder der Wohnort der Person außerhalb des Kreises liegt.\r\n\r\n[Mehr Daten und Diagramme zu Corona in Schleswig-Holstein](https://www.schleswig-holstein.de/DE/Schwerpunkte/Coronavirus/Zahlen/zahlen_node.html)",
    "en": "Time series of Corona numbers for Schleswig-Holstein\n\nThe following fields are included: \n\n— ‘date’ — date in format dd.mm.yyyy\n— ‘reported cases’\n— ‘hospitalisations’\n— ‘deceased’\n\nField separator is comma, string separator is double quote (\")\n\nThe data published here are based on the figures provided by the districts and non-circular cities by the official means of reporting to the Land Registration Office. As data collection and transmission takes time, deviations from the cases communicated on the spot may arise. In individual cases, there may also be a reduction in the reported cases, for example if a report has not been confirmed or if the person’s place of residence is outside the circle. \n \n[More data and charts on Corona in Schleswig-Holstein](https://www.schleswig-holstein.de/DE/Schwerpunkte/Coronavirus/Zahlen/zahlen_node.html)"
  },
  "Creator": {
    "IRI": "https://opendata.schleswig-holstein.de/organization/94498aaa-9bd0-4ac0-ae70-db319a3ca1d8"
  },
  "Publisher": [
    {
      "IRI": "https://opendata.schleswig-holstein.de/organization/94498aaa-9bd0-4ac0-ae70-db319a3ca1d8"
    }
  ],
  "Contributor": [
    {
      "IRI": "https://schleswig-holstein.de/opendata/",
      "Name": "Schleswig Holstein Open Data"
    }
  ],
  "Date Created": "2023-10-05T00:00:00Z",
  "Contact Point": {
    "E-Mail": "info@schleswig-holstein.de",
    "Name": "Landesmeldestelle Schleswig-Holstein"
  },
  "Base-URI": "https://phpefi.schleswig-holstein.de/corona/data202011/cvd_sh_verlauf.csv",
  "Identifier": "cvd_sh_verlauf",
  "Version": 1.0,
  "Work Status": "Published",
  "Visualize": true,
  "Accrual Periodicity": "daily",
  "Namespace": "https://phpefi.schleswig-holstein.de/corona",
  "dimensions": {
    "Datum": {
      "name": {
        "de": "Datum",
        "en": "Date"
      },
      "dimension-type": "Key Dimension",
      "scale-type": "ordinal",
      "path": "date",
      "description": {
        "en": "Date in format dd.mm.yyyy",
        "de": "Datum im Format TT.MM.JJJJ"
      },
      "mapping": {
        "type": "regex",
        "pattern": "(?P<day>[0-9]{2})\\.(?P<month>[0-9]{2})\\.(?P<year>[0-9]{4})",
        "replacement": "\\g<day>/\\g<month>/\\g<year>",
        "value-type": "Literal"
      }
    },
    "Gemeldete Fälle": {
      "name": {
        "de": "Gemeldete Fälle",
        "en": "Reported Cases"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "ratio",
      "path": "reported_cases",
      "description": {
        "en": "Number of reported cases"
      }
    },
    "Hospitalisierungen": {
      "name": {
        "de": "Hospitalisierungen",
        "en": "Hospitalisations"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "ratio",
      "path": "hospitalisations",
      "description": {
        "en": "Number of hospitalisations"
      }
    },
    "Verstorben": {
      "name": {
        "de": "Verstorben",
        "en": "Deceased"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "ratio",
      "path": "deceased",
      "description": {
        "en": "Number of deceased"
      }
    }
  }
}

=== Kronmar-Bafu/linpy/example/kita/description.json
{
  "$schema": "../../py_cube/description.schema.json",
  "Name": {
    "de": "Anzahl Kinder in Kindertagesstätten",
    "fr": "Nombre d'enfants dans les crèches",
    "it": "Numero di bambini negli asili nido",
    "en": "Number of kids in day care facilities"
  },
  "Description": {
    "de": "Ein Datensatz, der die Anzahl der Kinder in Kindertagesstätten enthält",
    "en": "A dataset containing the number of kids in day care facilities"
  },
  "Publisher": [
    {
      "IRI": "https://schleswig-holstein.de/opendata/org/office_of_daycare"
    }
  ],
  "Creator": {
    "IRI": "https://schleswig-holstein.de/opendata/org/office_of_daycare"
  },
  "Contributor": [
    {
      "IRI": "https://schleswig-holstein.de/opendata/org/office_of_daycare",
      "Name": "Bundesamt für Kindertagesstätten"
    }
  ],
  "Date Created": "2024-08-26T00:00:00.000Z",
  "Contact Point": {
    "E-Mail": "contact@daycare.ld.admin.ch",
    "Name": "Bundesamt für Kindertagesstätten"
  },
  "Base-URI": "https://daycare.ld.admin.ch/",
  "Identifier": "kids-daycare-facilities-per-lander",
  "Version": 1,
  "Work Status": "Draft",
  "Visualize": true,
  "Accrual Periodicity": "yearly",
  "Namespace": "mock",
  "dimensions": {
    "Land": {
      "name": {
        "de": "Land",
        "fr": "Etat",
        "it": "Stato",
        "en": "State"
      },
      "description": {
        "de": "Bundesland, in dem die Daten erhoben wurden"
      },
      "dimension-type": "Key Dimension",
      "scale-type": "nominal",
      "data-kind": {
        "type": "spatial-shape"
      },
      "path": "Land",
      "mapping": {
        "type": "additive",
        "base": "https://example.org/land/"
      }
    },
    "Jahr": {
      "name": {
        "de": "Jahr",
        "fr": "Année",
        "it": "Anno",
        "en": "Year"
      },
      "description": {
        "de": "Jahr der Erhebung",
        "fr": "Année du relevé",
        "it": "Anno di rilevamento",
        "en": "Year of survey"
      },
      "dimension-type": "Key Dimension",
      "scale-type": "ordinal",
      "path": "Jahr",
      "data-kind": {
        "type": "temporal",
        "unit": "year"
      },
      "mapping": {
        "type": "additive",
        "base": "https://ld.admin.ch/time/year/"
      }
    },
    "Kinder bis unter 3 Jahren": {
      "name": {
        "fr": "Nombre d'enfants de moins de 3 ans",
        "de": "Kinder bis unter 3 Jahren",
        "it": "Numero di bambini di età inferiore a 3 anni",
        "en": "Children under 3 years old"
      },
      "description": {
        "de": "Anzahl der Kinder bis unter 3 Jahren",
        "fr": "Nombre d'enfants de moins de 3 ans",
        "it": "Numero di bambini di età inferiore a 3 anni",
        "en": "Number of children under 3 years old"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "interval",
      "path": "Kinder-bis-unter-3-Jahren"
    },
    "Kinder von 3 bis unter 7 Jahren (ohne Schulkinder)": {
      "name": {
        "fr": "Nombre d'enfants de 3 à moins de 7 ans (sans enfants scolarisés)",
        "de": "Kinder von 3 bis unter 7 Jahren (ohne Schulkinder)",
        "it": "Numero di bambini da 3 a meno di 7 anni (senza bambini scolastici)",
        "en": "Children aged 3 to under 7 years (excluding school children)"
      },
      "description": {
        "de": "Anzahl der Kinder von 3 bis unter 7",
        "fr": "Nombre d'enfants de 3 à moins de 7 ans",
        "it": "Numero di bambini da  3 a meno di 7 anni",
        "en": "Number of children aged 3 to under 7"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "interval",
      "path": "Kinder-von-3-bis-unter-7-Jahren"
    },
    "Kinder von 5 bis unter 14 Jahren (nur Schulkinder)": {
      "name": {
        "fr": "Nombre d'enfants de 5 à moins de 14 ans (uniquement scolarisés)",
        "de": "Kinder von 5 bis unter 14 Jahren (nur Schulkinder)",
        "it": "Numero di bambini da 5 a meno di 14 anni (solo scolari)",
        "en": "Children aged 5 to under 14 years (school children only)"
      },
      "description": {
        "de": "Anzahl der Kinder von 5 bis unter 15",
        "fr": "Nombre d'enfants de 5 à moins de 14 ans",
        "it": "Numero di bambini da  5 a meno di 14 anni",
        "en": "Number of children aged 5 to under 14"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "interval",
      "path": "Kinder-von-5-bis-unter-14-Jahren"
    },
    "Kinder von 7 Jahren und älter (Nicht-schulkinder)": {
      "name": {
        "fr": "Nombre d'enfants de 7 ans et plus (non scolarisés)",
        "de": "Kinder von 7 Jahren und älter (Nicht-schulkinder)",
        "it": "Numero di bambini di 7 anni e più (non scolari)",
        "en": "Children aged 7 and older (non-school children)"
      },
      "description": {
        "de": "Anzahl der Kinder von 7 Jahren und älter (Nicht-schulkinder)",
        "fr": "Nombre d'enfants de 7 ans et plus (non scolarisés)",
        "it": "Numero di bambini di 7 anni e più (non scolari)",
        "en": "Number of children aged 7 and older (non-school children)"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "interval",
      "path": "Kinder-von-7-Jahren-und-älter"
    },
    "Insgesamt": {
      "name": {
        "fr": "Nombre total d'enfants",
        "de": "Gesamtzahl der Kinder",
        "it": "Numero totale di bambini",
        "en": "Total number of children"
      },
      "description": {
        "de": "Gesamtzahl der Kinder in Kindertagesstätten",
        "fr": "Nombre total d'enfants dans les crèches",
        "it": "Numero totale di bambini negli asili nido",
        "en": "Total number of children in day care facilities"
      },
      "dimension-type": "Measure Dimension",
      "scale-type": "interval",
      "path": "Insgesamt"
    }
  }
}
